---
title: "Untitled"
author: "MS"
date: '2022-05-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(afex)
library(dplyr)
library(magrittr)

#load packages
library('BayesFactor')
library(ggplot2)
library(plyr)
library(gridExtra)
library(extrafont)

source("../scripts/helpers.R")

list.files("../data/raw_data/", pattern = "u00215*")

```

# Study 1

data processing 

```{r}
#Reading Data----

SIdata = read.table('../data/raw_data/p00217_allSLTM1.txt',sep='') #Data for first part of experiment (stimulus identification)
LTMdata = read.table('../data/raw_data/p00217_allSLTM1LTM.txt',sep='') #Data for the second part of the experiment (long-term memory)

#Add column names
colnames(SIdata) = c('sub','block','trial','cue','rt','resp_pos','targ_pos','acc')
colnames(LTMdata) = c('sub','block','trial','cue','dec','acc','resp','rt')

#Make subject numbers factor
SIdata$sub = as.factor(SIdata$sub)
N = length(levels(SIdata$sub))
LTMdata$sub = as.factor(LTMdata$sub)

#Rename cues from 1s and 0s to actual name
SIdata$cue[SIdata$cue==1] = 'before'
SIdata$cue[SIdata$cue==2] = 'during'
LTMdata$cue[LTMdata$cue==1] = 'before'
LTMdata$cue[LTMdata$cue==2] = 'during'
LTMdata$cue[LTMdata$cue==0] = 'lure'

#Set confidence rating to be absolute value
LTMdata$resp = abs(LTMdata$resp)

#Data Cleaning----

#Remove outliers using boxplot (1.5xIQR)
boxplot(SIdata$rt)
IQRSI = IQR(SIdata$rt)
OutVals = boxplot(SIdata$rt,plot=FALSE)$out
SIdata = SIdata[!(SIdata$rt %in% OutVals),]
boxplot(SIdata$rt)

boxplot(LTMdata$rt)
IQRLTM = IQR(LTMdata$rt)
OutVals = boxplot(LTMdata$rt, plot=FALSE)$out
LTMdata = LTMdata[!(LTMdata$rt %in%OutVals),]
boxplot(LTMdata$rt)

#Reformat data
LTMdata$sub = factor(LTMdata$sub)
SIdata$sub = factor(SIdata$sub)
N = length(levels(LTMdata$sub))
levels(LTMdata$sub) = 1:N
N = length(levels(SIdata$sub))
levels(SIdata$sub) = 1:N


#Basic Stats SI----

#Accuracy
SIfull.dat = as.data.frame.table(tapply(SIdata$acc,list(SIdata$sub,SIdata$cue),mean))
colnames(SIfull.dat) = c('sub','cue','acc')

#RT
SIrt.dat = as.data.frame.table(tapply(SIdata$rt,list(SIdata$sub,SIdata$cue),mean))
colnames(SIrt.dat) = c('sub','cue','rt')
SIfull.dat$rt <- SIrt.dat[,3]

# **Summary SI----
SI.summary <- ddply(SIfull.dat,c("cue"),summarize,N=length(acc),meanACC=mean(acc),sdACC=sd(acc),seACC=sdACC/sqrt(N),
                 meanRT=mean(rt),sdRT=sd(rt),seRT=sdRT/sqrt(N))


#Basic Stats LTM----

#Accuracy
LTMfull.dat = as.data.frame.table(tapply(LTMdata$acc,list(LTMdata$sub,LTMdata$cue),mean))
colnames(LTMfull.dat) = c('sub','cue','acc')

#RT
LTMrt.dat = as.data.frame.table(tapply(LTMdata$rt,list(LTMdata$sub,LTMdata$cue),mean))
colnames(LTMrt.dat) = c('sub','cue','rt')
LTMfull.dat$rt <- LTMrt.dat[,3]

#Confidence
LTMconf.dat = as.data.frame.table(tapply(LTMdata$resp,list(LTMdata$sub,LTMdata$cue),mean))
colnames(LTMconf.dat) = c('sub','cue','resp')
LTMfull.dat$resp <- LTMconf.dat[,3]

# **Summary LTM----
LTM.summary <- ddply(LTMfull.dat,c("cue"),summarize,N=length(acc),meanACC=mean(acc),sdACC=sd(acc),seACC=sdACC/sqrt(N),
                 meanRT = mean(rt),sdRT=sd(rt),seRT=sdRT/sqrt(N),meanCON=mean(resp),sdCON=sd(resp),seCON=sdCON/sqrt(N))


```

models 

```{r}
#T Tests
t.test(x=SIfull.dat$acc[(SIfull.dat$cue=="before")],y=SIfull.dat$acc[(SIfull.dat$cue=="during")],paired=TRUE)
```
```{r}
SIfull.dat %>% 
  afex::aov_4(acc ~ cue + (cue|sub), data = .)
```


```{r}
p00217_mod_rm_z_1 <- SIfull.dat %>% 
  afex::aov_4(z(acc) ~ cue + (cue|sub), data = .)

key_effects = c("cue")
export_ols(p00217_mod_rm_z_1, key_effects)
```

lmer

```{r}
p00217_mod_lmer_z_1 <- SIfull.dat %>% 
  lme4::lmer(z(acc) ~ cue + (1|sub), data = .)

key_effects = c("cueduring")
export_ols(p00217_mod_lmer_z_1, key_effects)
```



```{r}
#Stat Tests LTM----
#T Tests
t.test(x=LTMfull.dat$acc[(LTMfull.dat$cue=="before")], y=LTMfull.dat$acc[(LTMfull.dat$cue=="during")],paired=TRUE)
```

```{r}
LTMfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  afex::aov_4(acc ~ cue + (cue|sub), data = ., 
              anova_table = list(
                correction = "none"
              )
  )

p00217_mod_rm_z_2 <- LTMfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  afex::aov_4(z(acc) ~ cue + (cue|sub), data = ., 
              anova_table = list(
                correction = "none"
              )
  )


key_effects = c("cue")
export_ols(p00217_mod_rm_z_2, key_effects)
```

lmer

```{r}
p00217_mod_lmer_z_2 <- LTMfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  lme4::lmer(z(acc) ~ cue + (1|sub), data = .
  )


key_effects = c("cueduring")
export_ols(p00217_mod_lmer_z_2, key_effects)
```




```{r}
#Confidence
t.test(x=LTMfull.dat$resp[(LTMfull.dat$cue=="before")], y=LTMfull.dat$resp[(LTMfull.dat$cue=="during")],paired=TRUE)
```

```{r}
LTMfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  afex::aov_4(resp ~ cue + (cue|sub), data = ., 
              anova_table = list(
                correction = "none"
              )
  )

p00217_mod_rm_z_3 <- LTMfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  afex::aov_4(z(resp) ~ cue + (cue|sub), data = ., 
              anova_table = list(
                correction = "none"
              )
  )

key_effects = c("cue")
export_ols(p00217_mod_rm_z_3, key_effects)
```
lmer

```{r}
p00217_mod_lmer_z_3 <- LTMfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  lme4::lmer(z(resp) ~ cue + (1|sub), data = .)

key_effects = c("cueduring")
export_ols(p00217_mod_lmer_z_3, key_effects)
```

# Study 2 

```{r}
#Reading Data----

SIdata = read.table('../data/raw_data/p00217_allSLTM2.txt',sep='') #Data for first part of experiment (stimulus identification)
LTMdata = read.table('../data/raw_data/p00217_allSLTM2LTM.txt',sep='') #Data for the second part of the experiment (long-term memory)

#Add column names
colnames(SIdata) = c('sub','block','trial','cue','rt','resp_pos','targ_pos','acc')
colnames(LTMdata) = c('sub','block','trial','cue','dec','acc','resp','rt')

#Make subject numbers factor
SIdata$sub = as.factor(SIdata$sub)
N = length(levels(SIdata$sub))
LTMdata$sub = as.factor(LTMdata$sub)

#Rename cues from 1s and 0s to actual name
SIdata$cue[SIdata$cue==1] = 'before'
SIdata$cue[SIdata$cue==2] = 'during'
LTMdata$cue[LTMdata$cue==1] = 'before'
LTMdata$cue[LTMdata$cue==2] = 'during'
LTMdata$cue[LTMdata$cue==0] = 'lure'

#Set confidence rating to be absolute value
LTMdata$resp = abs(LTMdata$resp)


#Data Cleaning----

#Manually remove participants that did not complete both tasks
SIdata=SIdata[(SIdata$sub!=26),]
SIdata=SIdata[(SIdata$sub!=30),]
SIdata=SIdata[(SIdata$sub!=32),]
SIdata=SIdata[(SIdata$sub!=33),]
SIdata=SIdata[(SIdata$sub!=35),]

LTMdata=LTMdata[(LTMdata$sub!=33),]
LTMdata=LTMdata[(LTMdata$sub!=35),]

#Remove outliers using boxplot (1.5xIQR)
boxplot(SIdata$rt)
IQRSI = IQR(SIdata$rt)
OutVals = boxplot(SIdata$rt,plot=FALSE)$out
SIdata = SIdata[!(SIdata$rt %in% OutVals),]
boxplot(SIdata$rt)

boxplot(LTMdata$rt)
IQRLTM = IQR(LTMdata$rt)
OutVals = boxplot(LTMdata$rt, plot=FALSE)$out
LTMdata = LTMdata[!(LTMdata$rt %in%OutVals),]
boxplot(LTMdata$rt)

#Reformat data
LTMdata$sub = factor(LTMdata$sub)
SIdata$sub = factor(SIdata$sub)
N = length(levels(LTMdata$sub))
levels(LTMdata$sub) = 1:N
N = length(levels(SIdata$sub))
levels(SIdata$sub) = 1:N


#Basic Stats SI----

#Accuracy
SIfull.dat = as.data.frame.table(tapply(SIdata$acc,list(SIdata$sub,SIdata$cue),mean))
colnames(SIfull.dat) = c('sub','cue','acc')

#RT
SIrt.dat = as.data.frame.table(tapply(SIdata$rt,list(SIdata$sub,SIdata$cue),mean))
colnames(SIrt.dat) = c('sub','cue','rt')
SIfull.dat$rt <- SIrt.dat[,3]

# **Summary SI----
SI.summary <- ddply(SIfull.dat,c("cue"),summarize,N=length(acc),meanACC=mean(acc),sdACC=sd(acc),seACC=sdACC/sqrt(N),
                  meanRT=mean(rt),sdRT=sd(rt),seRT=sdRT/sqrt(N))


#Basic Stats LTM----
#Accuracy
LTMfull.dat = as.data.frame.table(tapply(LTMdata$acc,list(LTMdata$sub,LTMdata$cue),mean))
colnames(LTMfull.dat) = c('sub','cue','acc')

#RT
LTMrt.dat = as.data.frame.table(tapply(LTMdata$rt,list(LTMdata$sub,LTMdata$cue),mean))
colnames(LTMrt.dat) = c('sub','cue','rt')
LTMfull.dat$rt <- LTMrt.dat[,3]

#Confidence
LTMconf.dat = as.data.frame.table(tapply(LTMdata$resp,list(LTMdata$sub,LTMdata$cue),mean))
colnames(LTMconf.dat) = c('sub','cue','resp')
LTMfull.dat$resp <- LTMconf.dat[,3]

# **Summary LTM----
LTM.summary <- ddply(LTMfull.dat,c("cue"),summarize,N=length(acc),meanACC=mean(acc),sdACC=sd(acc),seACC=sdACC/sqrt(N),
                   meanRT = mean(rt),sdRT=sd(rt),seRT=sdRT/sqrt(N),meanCON=mean(resp),sdCON=sd(resp),seCON=sdCON/sqrt(N))


```

```{r}
#T Tests
t.test(x=SIfull.dat$acc[(SIfull.dat$cue=="before")],y=SIfull.dat$acc[(SIfull.dat$cue=="during")],paired=TRUE)
```

```{r}
p00217_mod_rm_z_4 <- SIfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  afex::aov_4(z(acc) ~ cue + (cue|sub), data = ., 
              anova_table = list(
                correction = "none"
              )
  )

key_effects = c("cue")
export_ols(p00217_mod_rm_z_4, key_effects)
```

lmer

```{r}
p00217_mod_lmer_z_4 <- SIfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  lme4::lmer(z(acc) ~ cue + (1|sub), data = .
  )

key_effects = c("cueduring")
export_ols(p00217_mod_lmer_z_4, key_effects)
```



```{r}
#T Tests
t.test(x=LTMfull.dat$acc[(LTMfull.dat$cue=="before")], y=LTMfull.dat$acc[(LTMfull.dat$cue=="during")],paired=TRUE)
```

```{r}
p00217_mod_rm_z_5 <- LTMfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  afex::aov_4(z(acc) ~ cue + (cue|sub), data = ., 
              anova_table = list(
                correction = "none"
              )
  )

key_effects = c("cue")
export_ols(p00217_mod_rm_z_5, key_effects)
```
lmer

```{r}
p00217_mod_lmer_z_5 <- LTMfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  lme4::lmer(z(acc) ~ cue + (1|sub), data = .
  )

key_effects = c("cueduring")
export_ols(p00217_mod_lmer_z_5, key_effects)
```


```{r}
t.test(x=LTMfull.dat$resp[(LTMfull.dat$cue=="before")], y=LTMfull.dat$resp[(LTMfull.dat$cue=="during")],paired=TRUE)
```

```{r}
p00217_mod_rm_z_6 <- LTMfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  afex::aov_4(z(resp) ~ cue + (cue|sub), data = ., 
              anova_table = list(
                correction = "none"
              )
  )

key_effects = c("cue")
export_ols(p00217_mod_rm_z_6, key_effects)
```

lmer

```{r}
p00217_mod_lmer_z_6 <- LTMfull.dat %>% 
  dplyr::filter(cue %in% c("before", "during")) %>% 
  lme4::lmer(z(resp) ~ cue + (1|sub), data = .
  )

key_effects = c("cueduring")
export_ols(p00217_mod_lmer_z_6, key_effects)
```

# Study 3 

```{r}
#Reading Data----

SIdata = read.table('../data/raw_data/p00217_allSLTM4.txt',sep='') #Data for first part of experiment (stimulus identification)
LTMdata = read.table('../data/raw_data/p00217_allSLTM4LTM.txt',sep='') #Data for the second part of the experiment (long-term memory)

#Add column names
colnames(SIdata) = c('sub','block','trial','cue','word','rt','resp_pos','targ_pos','acc')
colnames(LTMdata) = c('sub','block','trial','cue','word','dec','acc','resp','rt')

#Make subject numbers factor
SIdata$sub = as.factor(SIdata$sub)
N = length(levels(SIdata$sub))
LTMdata$sub = as.factor(LTMdata$sub)

#Rename cues from 1s and 0s to actual name
SIdata$cue[SIdata$cue==1] = 'before'
SIdata$cue[SIdata$cue==2] = 'during'
LTMdata$cue[LTMdata$cue==1] = 'before'
LTMdata$cue[LTMdata$cue==2] = 'during'
LTMdata$cue[LTMdata$cue==0] = 'lure'

SIdata$word[SIdata$word==1] = 'word'
SIdata$word[SIdata$word==2] = 'nonword'
LTMdata$word[LTMdata$word==1] = 'word'
LTMdata$word[LTMdata$word==2] = 'nonword'
LTMdata$word[LTMdata$word==0] = 'lure'

#Set confidence rating to be absolute value
LTMdata$resp = abs(LTMdata$resp)

#Data Cleaning----

#Manually remove 2 participants that did not complete both tasks
SIdata=SIdata[(SIdata$sub!=11),]
SIdata=SIdata[(SIdata$sub!=14),]

#Remove outliers using boxplot (1.5xIQR)
boxplot(SIdata$rt)
IQRSI = IQR(SIdata$rt)
OutVals = boxplot(SIdata$rt,plot=FALSE)$out
SIdata = SIdata[!(SIdata$rt %in% OutVals),]
boxplot(SIdata$rt)

boxplot(LTMdata$rt)
IQRLTM = IQR(LTMdata$rt)
OutVals = boxplot(LTMdata$rt, plot=FALSE)$out
LTMdata = LTMdata[!(LTMdata$rt %in%OutVals),]
boxplot(LTMdata$rt)

#Reformat data
LTMdata$sub = factor(LTMdata$sub)
SIdata$sub = factor(SIdata$sub)
N = length(levels(LTMdata$sub))
levels(LTMdata$sub) = 1:N
N = length(levels(SIdata$sub))
levels(SIdata$sub) = 1:N


#Basic Stats SI----

#By Cue Type

#Accuracy
SIcue.dat = as.data.frame.table(tapply(SIdata$acc,list(SIdata$sub,SIdata$cue),mean))
colnames(SIcue.dat) = c('sub','cue','acc')

#RT
SIcuert.dat = as.data.frame.table(tapply(SIdata$rt,list(SIdata$sub,SIdata$cue),mean))
colnames(SIcuert.dat) = c('sub','cue','rt')
SIcue.dat$rt <- SIcuert.dat[,3]

#**Summary SI Cue----
SIcue.summary <- ddply(SIcue.dat,c("cue"),summarize,N=length(acc),meanACC=mean(acc),sdACC=sd(acc),seACC=sdACC/sqrt(N),
                 meanRT=mean(rt),sdRT=sd(rt),seRT=sdRT/sqrt(N))

#By Stimulus Type

#Accuracy
SIword.dat = as.data.frame.table(tapply(SIdata$acc,list(SIdata$sub,SIdata$word),mean))
colnames(SIword.dat) = c('sub','word','acc')

#RT
SIwordrt.dat = as.data.frame.table(tapply(SIdata$rt,list(SIdata$sub,SIdata$word),mean))
colnames(SIwordrt.dat) = c('sub','word','rt')
SIword.dat$rt <- SIwordrt.dat[,3]

#**Summary SI Stimulus----
SIword.summary <- ddply(SIword.dat,c("word"),summarize,N=length(acc),meanACC=mean(acc),sdACC=sd(acc),seACC=sdACC/sqrt(N),
                 meanRT=mean(rt),sdRT=sd(rt),seRT=sdRT/sqrt(N))

#By Cue Type x Stimulus Type

#Accuracy
SIfull.dat = as.data.frame.table(tapply(SIdata$acc,list(SIdata$sub,SIdata$cue,SIdata$word),mean))
colnames(SIfull.dat) = c('sub','cue','word','acc')

#RT
SIrt.dat = as.data.frame.table(tapply(SIdata$rt,list(SIdata$sub,SIdata$cue,SIdata$word),mean))
colnames(SIrt.dat) = c('sub','cue','word','rt')
SIfull.dat$rt <- SIrt.dat[,4]

#**Summary SI Cue x Stimulus----
SIfull.summary <- ddply(SIfull.dat,c("cue","word"),summarize,N=length(acc),meanACC=mean(acc),sdACC=sd(acc),seACC=sdACC/sqrt(N),
                 meanRT=mean(rt),sdRT=sd(rt),seRT=sdRT/sqrt(N))


#Basic Stats LTM----

#By Cue Type

#Accuracy
LTMcue.dat = as.data.frame.table(tapply(LTMdata$acc,list(LTMdata$sub,LTMdata$cue),mean,na.rm=TRUE))
colnames(LTMcue.dat) = c('sub','cue','acc')

#RT
LTMcuert.dat = as.data.frame.table(tapply(as.numeric(LTMdata$rt),list(LTMdata$sub,LTMdata$cue),mean,na.rm=TRUE))
colnames(LTMcuert.dat) = c('sub','cue','rt')
LTMcue.dat$rt<-(LTMcuert.dat[,3])

#Confidence
LTMcueconf.dat = as.data.frame.table(tapply(LTMdata$resp,list(LTMdata$sub,LTMdata$cue),mean,na.rm=TRUE))
colnames(LTMcueconf.dat) = c('sub','cue','resp')
LTMcue.dat$resp <- LTMcueconf.dat[,3]

#Remove combinations that don't exist (i.e., word x lure, etc.)
LTMcue.dat = LTMcue.dat[complete.cases(LTMcue.dat),]

#**Summary LTM Cue----
LTMcue.summary <- ddply(LTMcue.dat,c("cue"),summarize,N=length(acc),meanACC=mean(acc),sdACC=sd(acc),seACC=sdACC/sqrt(N),
                 meanRT=mean(rt),sdRT=sd(rt),seRT=sdRT/sqrt(N),meanCON=mean(resp),sdCON=sd(resp),seCON=sdCON/sqrt(N))

#By Stimulus Type

#Accuracy
LTMword.dat = as.data.frame.table(tapply(LTMdata$acc,list(LTMdata$sub,LTMdata$word),mean,na.rm=TRUE))
colnames(LTMword.dat) = c('sub','word','acc')

#RT
LTMwordrt.dat = as.data.frame.table(tapply(as.numeric(LTMdata$rt),list(LTMdata$sub,LTMdata$word),mean,na.rm=TRUE))
colnames(LTMwordrt.dat) = c('sub','word','rt')
LTMword.dat$rt <- (LTMwordrt.dat[,3])

#Confidence
LTMwordconf.dat = as.data.frame.table(tapply(LTMdata$resp,list(LTMdata$sub,LTMdata$word),mean,na.rm=TRUE))
colnames(LTMwordconf.dat) = c('sub','word','resp')
LTMword.dat$resp <- LTMwordconf.dat[,3]

#Remove combinations that don't exist (i.e., word x lure, etc.)
LTMword.dat = LTMword.dat[complete.cases(LTMword.dat),]

#**Summary LTM Stimulus----
LTMword.summary <- ddply(LTMword.dat,c("word"),summarize,N=length(acc),meanACC=mean(acc),sdACC=sd(acc),seACC=sdACC/sqrt(N),
                 meanRT=mean(rt),sdRT=sd(rt),seRT=sdRT/sqrt(N),meanCON=mean(resp),sdCON=sd(resp),seCON=sdCON/sqrt(N))

#By Cue Type x Stimulus Type

#Accuracy
LTMfull.dat = as.data.frame.table(tapply(LTMdata$acc,list(LTMdata$sub,LTMdata$cue,LTMdata$word),mean,na.rm=TRUE))
colnames(LTMfull.dat) = c('sub','cue','word','acc')

#RT
LTMrt.dat = as.data.frame.table(tapply(as.numeric(LTMdata$rt),list(LTMdata$sub,LTMdata$cue,LTMdata$word),mean,na.rm=TRUE))
colnames(LTMrt.dat) = c('sub','cue','word','rt')
LTMfull.dat$rt<-(LTMrt.dat[,4])

#Confidence
LTMconf.dat = as.data.frame.table(tapply(LTMdata$resp,list(LTMdata$sub,LTMdata$cue,LTMdata$word),mean,na.rm=TRUE))
colnames(LTMconf.dat) = c('sub','cue','word','resp')
LTMfull.dat$resp <- LTMconf.dat[,4]

#Remove combinations that don't exist (i.e., word x lure, etc.)
LTMfull.dat = LTMfull.dat[complete.cases(LTMfull.dat),]

#**Summary LTM Cue x Stimulus----
LTMfull.summary <- ddply(LTMfull.dat,c("cue","word"),summarize,N=length(acc),meanACC=mean(acc),sdACC=sd(acc),seACC=sdACC/sqrt(N),
                 meanRT=mean(rt),sdRT=sd(rt),seRT=sdRT/sqrt(N),meanCON=mean(resp),sdCON=sd(resp),seCON=sdCON/sqrt(N))


```

```{r}
summary(aov(acc~(cue*word)+Error(sub/(cue*word)),data=SIfull.dat))
```

```{r}
SIfull.dat %>% 
  afex::aov_4(acc ~ cue*word + (cue*word|sub), 
              data = .,)

p00217_mod_rm_z_7 <- SIfull.dat %>% 
  afex::aov_4(z(acc) ~ cue*word + (cue*word|sub), 
              data = .,)

key_effects = c("cue", "word", "cue:word")
export_ols(p00217_mod_rm_z_7, key_effects)
```
lmer

```{r}
p00217_mod_lmer_z_7 <- SIfull.dat %>% 
  lme4::lmer(z(acc) ~ cue*word + (1|sub), 
              data = .,)

key_effects = c("cueduring", "wordword", "cueduring:wordword")
export_ols(p00217_mod_lmer_z_7, key_effects)
```



```{r}
summary(aov(acc~(cue*word)+Error(sub/(cue*word)), data=LTMfull.dat[(LTMfull.dat$cue!="lure"),]))
```

```{r}
p00217_mod_rm_z_8 <- LTMfull.dat %>% 
  dplyr::filter(cue!="lure") %>% 
  afex::aov_4(z(acc) ~ cue*word + (cue*word|sub), 
              data = .)

key_effects = c("cue", "word", "cue:word")
export_ols(p00217_mod_rm_z_8, key_effects)
```
lmer

```{r}
p00217_mod_lmer_z_8 <- LTMfull.dat %>% 
  dplyr::filter(cue!="lure") %>% 
  lme4::lmer(z(acc) ~ cue*word + (1|sub), 
              data = .)

key_effects = c("cueduring", "wordword", "cueduring:wordword")
export_ols(p00217_mod_lmer_z_8, key_effects)
```


```{r}
summary(aov(resp~(cue*word)+Error(sub/(cue*word)), data=LTMfull.dat[(LTMfull.dat$cue!="lure"),]))
```


```{r}
p00217_mod_rm_z_9 <- LTMfull.dat %>% 
  dplyr::filter(cue!="lure") %>% 
  afex::aov_4(z(resp) ~ cue*word + (cue*word|sub), 
              data = .)

key_effects = c("cue", "word", "cue:word")
export_ols(p00217_mod_rm_z_9, key_effects)
```

```{r}
p00217_mod_lmer_z_9 <- LTMfull.dat %>% 
  dplyr::filter(cue!="lure") %>% 
  lme4::lmer(z(resp) ~ cue*word + (1|sub), 
              data = .)

key_effects = c("cueduring", "wordword", "cueduring:wordword")
export_ols(p00217_mod_lmer_z_9, key_effects)
```



