---
title: "Untitled"
author: "MS"
date: '2022-05-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(afex)
library(dplyr)
library(magrittr)

source("../scripts/helpers.R")

list.files("../data/raw_data/", pattern = "p00319*")

p00319_tib_1 <- read.csv("../data/raw_data/p00319_data.csv", stringsAsFactors=FALSE, fileEncoding="latin1")

p00319_tib_1$purposenote_control <- ifelse(p00319_tib_1$purposenote_planned==1, 0, 1)

```

```{r}
p00319_tib_1
```

main model 

```{r}
p00319_tib_1 %>% 
  dplyr::filter(purpose_pretreatment_miss > 0) %>% 
  lm(notegrade~online*purposenote_planned*nonnative_english+  # Three higher-order interactions of interest
                 trust_pretreatment_miss*purpose_pretreatment_miss*engteacherpurpose_pretreatment_miss+ 
                 as.factor(teacher),data =.) %>% 
  car::Anova()
```

```{r}
p00319_tib_1 %>% 
  dplyr::filter(purpose_pretreatment_miss > 0) %>% 
  lm(notegrade~online*purposenote_planned*nonnative_english+  # Three higher-order interactions of interest
                 trust_pretreatment_miss*purpose_pretreatment_miss*engteacherpurpose_pretreatment_miss+ 
                 as.factor(teacher),data =.) %>% 
  summary()


p00319_mod_z_1 <- p00319_tib_1 %>% 
  dplyr::filter(purpose_pretreatment_miss > 0) %>% 
  lm(z(notegrade)~factor(online)*factor(purposenote_planned)*factor(nonnative_english) +  # Three higher-order interactions of interest
                 z(trust_pretreatment_miss)*z(purpose_pretreatment_miss)*z(engteacherpurpose_pretreatment_miss)+ 
                 as.factor(teacher),data =.) 

key_effects = c("factor(online)1:factor(purposenote_planned)1", "factor(online)1:factor(purposenote_planned)1:factor(nonnative_english)1")
export_ols(p00319_mod_z_1, key_effects)
```


break down the interaction

mod 1

```{r}
p00319_tib_1$native <- ifelse(p00319_tib_1$nonnative_english==1, 0, 1)

p00319_tib_1 %>% 
  (lm(notegrade~online*purposenote_planned*native+  # Three higher-order interactions of interest
                        trust_pretreatment_miss*purpose_pretreatment_miss*engteacherpurpose_pretreatment_miss+
                        as.factor(teacher),
           data=.)) 

p00319_mod_z_2 <- p00319_tib_1 %>% 
  lm(z(notegrade)~factor(online)*factor(purposenote_planned)*factor(native) +  # Three higher-order interactions of interest
                        z(trust_pretreatment_miss)*z(purpose_pretreatment_miss)*z(engteacherpurpose_pretreatment_miss)+
                        as.factor(teacher),
      data=.)

key_effects = c("factor(online)1:factor(purposenote_planned)1")
export_ols(p00319_mod_z_2, key_effects)
```


mod 2

```{r}
p00319_tib_1 %>% 
  lm(notegrade~online*purposenote_planned*nonnative_english+  # Three higher-order interactions of interest
                        trust_pretreatment_miss*purpose_pretreatment_miss*engteacherpurpose_pretreatment_miss+
                        as.factor(teacher),
     data=.) %>% summary()


p00319_mod_z_3 <- p00319_tib_1 %>% 
  lm(z(notegrade)~factor(online)*factor(purposenote_planned)*factor(nonnative_english)+  # Three higher-order interactions of interest
                        z(trust_pretreatment_miss)*z(purpose_pretreatment_miss)*z(engteacherpurpose_pretreatment_miss)+
                        as.factor(teacher),
     data=.) 



key_effects = c("factor(online)1:factor(purposenote_planned)1")
export_ols(p00319_mod_z_3, key_effects)
```

