---
title: "Untitled"
author: "MS"
date: '2022-06-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../scripts/helpers.R")

df <- readxl::read_xlsx("../data/raw_data/p00655_Creativity_data.xlsx") %>% 
  dplyr::mutate(
    CAQ_score = as.numeric(CAQ_score), 
    condition = factor(condition))

df

```

1 

```{r}
p00655_mod_z_1 <- df %>% 
  lm(z(Fluency) ~ z(AUCi_RSA_36) + z(CAQ_score), .) 

export_ols(p00655_mod_z_1, 
           key_effects = c("z(AUCi_RSA_36)"))

```

2

```{r}
p00655_mod_z_2 <- df %>% 
  lm(z(Uniqueness) ~ z(AUCi_RSA_36) + z(CAQ_score), .) 

export_ols(p00655_mod_z_2, 
           key_effects = c("z(AUCi_RSA_36)"))
```

3

```{r}
p00655_mod_z_3 <- df %>% 
  lm(z(Flexibility) ~ z(AUCi_RSA_36) + z(CAQ_score), .) 

export_ols(p00655_mod_z_3, 
           key_effects = c("z(AUCi_RSA_36)"))
```


ancovas: 

4

```{r}
p00655_mod_z_4 <- df %>% 
  lm(z(Fluency) ~ condition  + z(CAQ_score), .) 

export_ols(p00655_mod_z_4, 
           key_effects = c("condition2", "condition3"))
```

5

```{r}
p00655_mod_z_5 <- df %>% 
  lm(z(Uniqueness) ~ condition  + z(CAQ_score), .) 

export_ols(p00655_mod_z_5, 
           key_effects = c("condition2", "condition3"))
```

6


```{r}
p00655_mod_z_6 <- df %>% 
  lm(z(Flexibility) ~ condition  + z(CAQ_score), .) 

export_ols(p00655_mod_z_6, 
           key_effects = c("condition2", "condition3"))
```

