---
title: "Untitled"
author: "MS"
date: '2022-07-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

df_1 <- readRDS("../data/raw_data/p01308_all_kart.rds")
df_2 <- readRDS("../data/raw_data/p01308_both.rds")
df_3 <- readRDS("../data/raw_data/p01308_both3.rds")
```


model 1 

```{r}
df_1 <- df_1 |> dplyr::mutate(
  column = factor(column, ordered = FALSE)
)
```


```{r}
p01308_mod_rm_z_1 <- df_1 %>% 
  afex::aov_4(z(itemsec) ~ cond*column + (cond*column|subject), .)

export_ols(p01308_mod_rm_z_1, 
           key_effects = c("cond:column"))


p01308_mod_lmer_z_1 <- df_1 %>% 
  lme4::lmer(z(itemsec) ~ cond*column + (1|subject), .)

export_ols(p01308_mod_lmer_z_1, 
           key_effects = c("condXXX:column2", "condXXX:column3"))
```

model 2 

```{r}
df_2 <- df_2 |> 
  dplyr::mutate(
    column = factor(column, ordered = FALSE)
  )
```


```{r}
p01308_mod_rm_z_2 <- df_2 %>% 
  afex::aov_4(z(itemsec) ~ task*cond*column + (task*cond*column|subject), .)


export_ols(p01308_mod_rm_z_2, 
           key_effects = c("task:cond", "task:column", "cond:column", 
                           "task:cond:column"))


p01308_mod_lmer_z_2 <- df_2 %>% 
  lme4::lmer(z(itemsec) ~ task*cond*column + (1|subject), .)


export_ols(p01308_mod_lmer_z_2, 
           key_effects = c("taskmem:condctr",
                           "taskmem:condinc" , "taskmem:condxbl" ,
                           "taskmem:column2", "taskmem:column3", "condctr:column2", "condinc:column2", "condxbl:column2",
                           "condctr:column3", "condinc:column3", "condxbl:column3", "taskmem:condctr:column2", "taskmem:condinc:column2", 
                           "taskmem:condxbl:column2",  "taskmem:condctr:column3",  "taskmem:condinc:column3",  "taskmem:condxbl:column3"
                           ))
```

model 3 

```{r}
df_3 <- df_3 |> 
  dplyr::mutate(
    column = factor(column, ordered = FALSE)
  )
```

```{r}
p01308_mod_rm_z_3 <- df_3 %>% 
  afex::aov_4(z(itemsec) ~ task*cond*column + (task*cond*column|subject), .)


export_ols(p01308_mod_rm_z_3, 
           key_effects = c("task:cond", "task:column", "cond:column", 
                           "task:cond:column"))


p01308_mod_lmer_z_3 <- df_3 %>% 
  lme4::lmer(z(itemsec) ~ task*cond*column + (1|subject), .)


export_ols(p01308_mod_lmer_z_3, 
           key_effects = mod_coeffs(p01308_mod_lmer_z_3)[7:23])


```

