---
title: "Untitled"
author: "MS"
date: '2022-07-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../scripts/helpers.R")

df_1 <- haven::read_sav("../data/raw_data/p01530_Data - Study 1 - updated.sav") %>% dplyr::mutate(id = 1:nrow(.))
df_2 <- haven::read_sav("../data/raw_data/p01530_Data - Study 2 - updated.sav") %>% dplyr::mutate(id = 1:nrow(.))
df_3 <- haven::read_sav("../data/raw_data/p01530_Data - Study 3 - updated.sav") %>% dplyr::mutate(id = 1:nrow(.))
df_4 <- haven::read_sav("../data/raw_data/p01530_Data - Study 4.sav") %>% dplyr::mutate(id = 1:nrow(.))
```

# exp 1 

```{r}
t.test(df_1$total_rt, df_1$total_ts, var.equal = T, paired = T)

df_1_long <- df_1 %>% 
  dplyr::select(id, contains("total")) %>% 
  tidyr::pivot_longer(-id)

p01530_mod_rm_z_1 <- df_1_long %>% 
  afex::aov_4(z(value) ~ name + (name|id), .)

export_ols(
  p01530_mod_rm_z_1, 
  key_effects = c("name")
)

p01530_mod_lmer_z_1 <- df_1_long %>% 
  lme4::lmer(z(value) ~ name + (1|id), .)

export_ols(
  p01530_mod_lmer_z_1, 
  key_effects = c("nametotal_ts")
)

```

# exp 2 

```{r}
df_2_long <- df_2 %>% 
  dplyr::select(id, contains("Total"))  %>% 
  tidyr::pivot_longer(-id) %>% 
  dplyr::mutate(name = factor(name, levels = c("TotalTS", "TotalRT", "TotalGI")))

ts_vs_other <- c(2/3, -1/3, -1/3)
rt_vs_gi <- c(0, -1/2, 1/2)

contrasts(df_2_long$name) <- cbind(ts_vs_other, rt_vs_gi)

p01530_mod_rm_z_2 <- df_2_long %>% 
  afex::aov_4(z(value) ~ name + (name|id), ., 
              anova_table = list(correction = "none"))

export_ols(
  p01530_mod_rm_z_2, 
  key_effects = "name"
)

p01530_mod_lmer_z_2 <- df_2_long %>% 
  lme4::lmer(z(value) ~ name + (1|id), .)

export_ols(
  p01530_mod_lmer_z_2, 
  key_effects = c("namets_vs_other", "namert_vs_gi")
)
```

# exp 3 

note that this is incorrectly reported in the paper 

```{r}
t.test(df_3$TStotalMFQ, df_3$AStotalMFQ, paired = T, var.equal = T)

df_3_long <- df_3 %>% 
  dplyr::select(id, TStotalMFQ, AStotalMFQ) %>% 
  tidyr::pivot_longer(-id)

p01530_mod_rm_z_3 <- df_3_long %>% 
  afex::aov_4(z(value) ~ name + (name|id), .)

export_ols(
  p01530_mod_rm_z_3, 
  key_effects = "name"
)

p01530_mod_lmer_z_3 <- df_3_long %>% 
  lme4::lmer(z(value) ~ name + (1|id), .)

export_ols(
  p01530_mod_lmer_z_3, 
  key_effects = "nameTStotalMFQ"
)
```

# exp 4 

GLM totTS totRT totAS
  /WSFACTOR=factor1 3 Helmert 
  /METHOD=SSTYPE(3)
  /EMMEANS=TABLES(OVERALL) 
  /EMMEANS=TABLES(factor1) COMPARE ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=factor1.
  
```{r}
df_4_long <- df_4 %>% 
  dplyr::select(id, totTS, totRT, totAS) %>% 
  tidyr::pivot_longer(-id) %>% 
  dplyr::mutate(
    name = factor(name, levels = c("totTS", "totRT", "totAS"))
  )

p01530_mod_rm_z_4 <- df_4_long %>% 
  afex::aov_4(z(value) ~ name + (name|id), .)

export_ols(
  p01530_mod_rm_z_4, 
  key_effects = c("name")
)


p01530_mod_lmer_z_4 <- df_4_long %>% 
 lme4::lmer(z(value) ~ name + (1|id), .)

export_ols(
  p01530_mod_lmer_z_4, 
  key_effects = c("nametotRT", "nametotAS")
)
```


