---
title: "Untitled"
author: "MS"
date: '2022-05-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(afex)
library(dplyr)
library(magrittr)

source("../scripts/helpers.R")

list.files("../data/raw_data/", pattern = "u00161*")

u00161_tib_1 <- readxl::read_excel("../data/raw_data/u00161_salahub2020_AllBehavioral.xlsx")
u00161_tib_1
```

# Behavioural 

```{r}
u00161_tib_1_long <- u00161_tib_1 %>% 
  tidyr::pivot_longer(
    cols = -c(Participant, State, Trait, MaxK), 
    names_to = "condition", 
    values_to = "rt"
  ) %>% 
  dplyr::mutate(
    rt = as.numeric(rt), 
    condition = factor(condition, 
                       levels = c("NeutralRT", "NegativeRT", "PositiveRT"))
  )
```



```{r}
u00161_tib_1_long %>% 
  afex::aov_4(rt ~ condition + (condition|Participant), 
              data = .)


u00161_tib_1_long %>% 
  afex::aov_4(z(rt) ~ condition + (condition|Participant), 
              data = .)
```

```{r}
u00161_mod_rm_z_1 <- u00161_tib_1_long %>% 
  afex::aov_4(z(rt) ~ condition + (condition|Participant), 
              data = .)

key_effects = c("condition")
export_ols(u00161_mod_rm_z_1, key_effects)



u00161_mod_lmer_z_1 <- u00161_tib_1_long %>% 
  lme4::lmer(z(rt) ~ condition + (1|Participant), 
              data = .)

key_effects = c("conditionNegativeRT", "conditionPositiveRT")
export_ols(u00161_mod_lmer_z_1, key_effects)
```

