---
title: "u01114"
author: "MS"
date: '2022-06-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../scripts/helpers.R")

df <- read.csv("../data/raw_data/u01114_data for analysis.csv")

df_1 <- df %>% 
  dplyr::mutate(
    across(.cols = where(is.character), 
           .fns = readr::parse_number)
  ) 

df <- cbind(df[, 1:4], df_1[5:ncol(df_1)])
```


# 1

```{r}
df_intense_long <- df  %>% 
  dplyr::mutate(
    intense_proto_change = intense_proto_test-intense_proto_base, 
    intense_amb_change = intense_amb_test-intense_amb_base
  ) %>% 
  dplyr::select(id, group, intense_proto_change, intense_amb_change) %>% 
  tidyr::pivot_longer(cols = -c(id, group))


u01114_mod_rm_z_1 <- df_intense_long %>% 
  afex::aov_4(z(value) ~ group*name + (name|id), .)

export_ols(u01114_mod_rm_z_1, 
           key_effects = c("group", "name", "group:name"))


u01114_mod_lmer_z_1 <- df_intense_long %>% 
  lme4::lmer(z(value) ~ group*name + (1|id), .)

export_ols(u01114_mod_lmer_z_1, 
           key_effects = c("groupview", "nameintense_proto_change",
                           "groupview:nameintense_proto_change"))
```


# 2 

```{r}
df_scl_long <- df  %>% 
  dplyr::mutate(
    scl_proto_change = scl_proto_test-scl_proto_base, 
    scl_amb_change = scl_amb_test-scl_amb_base
  ) %>% 
  dplyr::select(id, group, scl_proto_change, scl_amb_change) %>% 
  tidyr::pivot_longer(cols = -c(id, group)) %>% 
  dplyr::filter(!id %in% c(4,5,6,17,25))


u01114_mod_rm_z_2 <- df_scl_long %>% 
  afex::aov_4(z(value) ~ group*name + (name|id), .)

export_ols(u01114_mod_rm_z_2, 
           key_effects = c("group", "name", "group:name"))


u01114_mod_lmer_z_2 <- df_scl_long %>% 
  lme4::lmer(z(value) ~ group*name + (1|id), .)

export_ols(u01114_mod_lmer_z_2, 
           key_effects = c("groupview", "namescl_proto_change",
                           "groupview:namescl_proto_change"))
```

# 3 

```{r}
df_scr_long <- df  %>% 
  dplyr::mutate(
    scr_proto_change = scr_proto_test-scr_proto_base, 
    scr_amb_change = scr_amb_test-scr_amb_base
  ) %>% 
  dplyr::select(id, group, scr_proto_change, scr_amb_change) %>% 
  tidyr::pivot_longer(cols = -c(id, group)) %>% 
  dplyr::filter(!id %in% c(4,5,6,17,25))




u01114_mod_rm_z_3 <- df_scr_long %>% 
  afex::aov_4(z(value) ~ group*name + (name|id), .)

export_ols(u01114_mod_rm_z_3, 
           key_effects = c("group", "name", "group:name"))


u01114_mod_lmer_z_3 <- df_scr_long %>% 
  lme4::lmer(z(value) ~ group*name + (1|id), .)

export_ols(u01114_mod_lmer_z_3, 
           key_effects = c("groupview", "namescr_proto_change",
                           "groupview:namescr_proto_change"))
```


