---
title: "Untitled"
author: "MS"
date: '2022-08-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../scripts/helpers.R")

df_1 <- readRDS("../data/raw_data/u01454_d_exp1.rds")
df_2 <- readRDS("../data/raw_data/u01454_d_exp2.rds")
df_3 <- readRDS("../data/raw_data/u01454_d_exp2b.rds")
```


# study 1 

model 1 

```{r}
aov_ez("ID","duration", df_1, within=c("congruency", "walking"), return = afex_options("return_aov"))


u01454_mod_rm_z_1 <- df_1 %>% 
  afex::aov_4(z(duration) ~ congruency*walking + (congruency*walking|ID), .)

export_ols(u01454_mod_rm_z_1, "congruency:walking")

u01454_mod_lmer_z_1 <- df_1 %>% 
  lme4::lmer(z(duration) ~ congruency*walking + (1|ID), .)

export_ols(u01454_mod_lmer_z_1, "congruencyincongruent:walkingforward")
```

# study 2 

model 2 

```{r}
u01454_mod_rm_z_2 <- df_2 %>% 
  afex::aov_4(z(duration) ~ congruency*walking + (congruency*walking|ID), .)

export_ols(u01454_mod_rm_z_2, "congruency:walking")

u01454_mod_lmer_z_2 <- df_2 %>% 
  lme4::lmer(z(duration) ~ congruency*walking + (1|ID), .)

export_ols(u01454_mod_lmer_z_2, "congruencyincongruent:walkingforward")
```

model 3 

```{r}
df_3 <- df_3 |> 
  dplyr::mutate(
    walking = factor(walking, ordered = FALSE), 
    congruency = factor(congruency, ordered = FALSE)
  )
```


```{r}
u01454_mod_rm_z_3 <- df_3 %>% 
  afex::aov_4(z(duration) ~ congruency*walking + (congruency*walking|ID), .)

export_ols(u01454_mod_rm_z_3, "congruency:walking")

u01454_mod_lmer_z_3 <- df_3 %>% 
  lme4::lmer(z(duration) ~ congruency*walking + (1|ID), .)

export_ols(u01454_mod_lmer_z_3, "congruencycongruent:walkingbackward")
```

