---
title: "Untitled"
author: "MS"
date: '2022-06-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../scripts/helpers.R")

df_1 <- readxl::read_xlsx("../data/raw_data/u01401_data_e1.xlsx")
df_2 <- readxl::read_xlsx("../data/raw_data/u01401_data_e2.xlsx")
```

# Study 1 

## 1 

```{r}
df_1_long_1 <- df_1 %>% 
  dplyr::select(id = Subj, LELTInit:`HEHT+Retr`) %>% 
  tidyr::pivot_longer(-id) %>% 
  dplyr::mutate(
    info = case_when(
      str_detect(name, "LELT") ~ "LELT",
      str_detect(name, "LEHT") ~ "LEHT",
      str_detect(name, "HELT") ~ "HELT",
      str_detect(name, "HEHT\\+") ~ "HEHT+",
      str_detect(name, "HEHT") ~ "HEHT", 
    ), 
    cond = case_when(
      str_detect(name, "Init") ~ "init",
      str_detect(name, "Retr") ~ "retr",
    )
  )


u01401_mod_rm_z_1 <- df_1_long_1 %>% 
  afex::aov_4(z(value) ~ info*cond + (info*cond|id), ., 
              anova_table = list(correction = "none"))

export_ols(u01401_mod_rm_z_1, 
           key_effects = c("info", "cond", "info:cond"))



u01401_mod_lmer_z_1 <- df_1_long_1 %>% 
  lme4::lmer(z(value) ~ info*cond + (1|id), .)

export_ols(u01401_mod_lmer_z_1, 
           key_effects = c("infoHEHT+", "infoHELT", "infoLEHT", 
                           "infoLELT", "condretr", "infoHEHT+:condretr", 
                           "infoHELT:condretr", "infoLELT:condretr"))
```

## 2 

```{r}
df_1_long_2 <- df_1 %>% 
  dplyr::select(id = Subj, NoR:`HEHT+`) %>% 
  tidyr::pivot_longer(-id) %>% 
  dplyr::mutate(
    name = factor(name, levels = c("NoR", "LELT", "LEHT", 
                                   "HELT", "HEHT", "HEHT+"))
  )
  


u01401_mod_rm_z_2 <- df_1_long_2 %>% 
  dplyr::filter(id != 46) %>% 
  afex::aov_4(z(value) ~ name + (name|id), ., 
              anova_table = list(correction = "none"))
  
export_ols(u01401_mod_rm_z_2, 
           key_effects = c("name"))


u01401_mod_lmer_z_2 <- df_1_long_2 %>% 
  dplyr::filter(id != 46) %>% 
  lme4::lmer(z(value) ~ name + (1|id), .)

export_ols(u01401_mod_lmer_z_2, 
           key_effects = c("nameLELT", "nameLEHT", "nameHELT", 
                           "nameHEHT", "nameHEHT+"))
  
```

## 3 

```{r}
df_1_long_3 <- df_1_long_2 %>% 
  dplyr::filter(!name %in% c("NoR", "HEHT+")) %>% 
  dplyr::mutate(
    expert = case_when(
      name %in% c("LELT", "LEHT") ~ "low", 
      name %in% c("HELT", "HEHT") ~ "high", 
    ), 
    trust = case_when(
      name %in% c("LELT", "HELT") ~ "low", 
      name %in% c("LEHT", "HEHT") ~ "high", 
    )
  )

u01401_mod_rm_z_3 <- df_1_long_3 %>% 
  afex::aov_4(z(value) ~ expert*trust + (expert*trust|id), .)

export_ols(u01401_mod_rm_z_3, 
           key_effects = c("expert", "trust", "expert:trust"))


u01401_mod_lmer_z_3 <- df_1_long_3 %>% 
  lme4::lmer(z(value) ~ expert*trust + (1|id), .)

export_ols(u01401_mod_lmer_z_3, 
           key_effects = c("expertlow", "trustlow", "expertlow:trustlow"))
```


# Study 2 

## 4

```{r}
df_2_long_1 <- df_2 %>% 
  dplyr::select(id = Subj, MCnoR:RChi) %>% 
  tidyr::pivot_longer(-id) %>% 
  dplyr::filter(
    !id %in% c(20, 67, 68)
  ) %>% 
  dplyr::mutate(
    name = factor(name, levels = c("MCnoR", "MClo", "MChi", "RClo", "RChi"))
  )

u01401_mod_rm_z_4 <- df_2_long_1 %>% 
  afex::aov_4(z(value) ~ name + (name|id), .)

export_ols(u01401_mod_rm_z_4, 
           key_effects = c("name"))


u01401_mod_lmer_z_4 <- df_2_long_1 %>% 
  lme4::lmer(z(value) ~ name + (1|id), .)

export_ols(u01401_mod_lmer_z_4, 
           key_effects = c("nameMClo", "nameMChi", "nameRClo", "nameRChi"))
```

## 5

```{r}
df_2_long_2 <- df_2 %>% 
  dplyr::select(id = Subj, noMI:TWhi) %>% 
  tidyr::pivot_longer(-id) %>% 
  dplyr::mutate(name = factor(name, levels = c("noMI", "noR", "TWlo", "TWhi")))

noMI_vs_all <- c(-3/4, 1/4, 1/4, 1/4)
noR_vs_tw <- c(0, -2/3, 1/3, 1/3)
low_vs_high <- c(0, 0, -1/2, 1/2)

contrasts(df_2_long_2$name) <- cbind(noMI_vs_all, noR_vs_tw, low_vs_high)

u01401_mod_rm_z_5 <- df_2_long_2 %>% 
  afex::aov_4(z(value) ~ name + (name|id), .)

export_ols(u01401_mod_rm_z_5, 
           key_effects = c("name"))


u01401_mod_lmer_z_5 <- df_2_long_2 %>% 
  lme4::lmer(z(value) ~ name + (1|id), .)

export_ols(u01401_mod_lmer_z_5, 
           key_effects = c("namenoMI_vs_all", "namenoR_vs_tw", "namelow_vs_high"))
```

