---
title: "u01569"
author: "MS"
date: '2022-06-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../scripts/helpers.R")

df_1 <- read.csv("../data/raw_data/u01569_exp1.csv")
df_2 <- read.csv("../data/raw_data/u01569_exp2.csv")
df_3 <- read.csv("../data/raw_data/u01569_exp3.csv")
df_4 <- read.csv("../data/raw_data/u01569_exp4.csv")
```


# Study 1

```{r}
df_1_long <- df_1 %>% 
  dplyr::select(id, contains("Att_")) %>% 
  tidyr::pivot_longer(-id) %>% 
  dplyr::mutate(
    att = if_else(str_detect(name, "endo"), "endo", "exo"), 
    cue = factor(readr::parse_number(name))
  )

u01569_mod_rm_z_1 <- df_1_long %>% 
  afex::aov_4(z(value) ~ att*cue + (att*cue|id), .)

export_ols(u01569_mod_rm_z_1, 
           key_effects = c("att", "cue", "att:cue"))


u01569_mod_lmer_z_1 <- df_1_long %>% 
  lme4::lmer(z(value) ~ att*cue + (1|id), .)

export_ols(u01569_mod_lmer_z_1, 
           key_effects = c("attexo", "cue2", "attexo:cue2"))
```

# Study 2

```{r}
df_2_long <- df_2 %>% 
  tidyr::pivot_longer(-id) %>% 
  dplyr::mutate(
    att = if_else(str_detect(name, "endo"), "endo", "exo"), 
    cue = factor(readr::parse_number(name))
  )



u01569_mod_rm_z_2 <- df_2_long %>% 
  afex::aov_4(z(value) ~ att*cue + (att*cue|id), .)

export_ols(u01569_mod_rm_z_2, 
           key_effects = c("att", "cue", "att:cue"))


u01569_mod_lmer_z_2 <- df_2_long %>% 
  lme4::lmer(z(value) ~ att*cue + (1|id), .)

export_ols(u01569_mod_lmer_z_2, 
           key_effects = c("attexo", "cue2", "attexo:cue2"))
```

# Study 3

```{r}
df_3_long <- df_3 %>% 
  tidyr::pivot_longer(-id) %>% 
  dplyr::mutate(
    att = if_else(str_detect(name, "endo"), "endo", "exo"), 
    cue = factor(readr::parse_number(name))
  )


u01569_mod_rm_z_3 <- df_3_long %>% 
  afex::aov_4(z(value) ~ att*cue + (att*cue|id), .)

export_ols(u01569_mod_rm_z_3, 
           key_effects = c("att", "cue", "att:cue"))


u01569_mod_lmer_z_3 <- df_3_long %>% 
  lme4::lmer(z(value) ~ att*cue + (1|id), .)

export_ols(u01569_mod_lmer_z_3, 
           key_effects = c("attexo", "cue2", "attexo:cue2"))
```

# Study 4

```{r}
df_4_long <- df_4 %>% 
  tidyr::pivot_longer(-id) %>% 
  dplyr::mutate(
    cond = factor(readr::parse_number(name))
  )

u01569_mod_rm_z_4 <- df_4_long %>% 
  afex::aov_4(z(value) ~ cond + (cond|id), .)

export_ols(u01569_mod_rm_z_4, 
           key_effects = "cond")


u01569_mod_lmer_z_4 <- df_4_long %>% 
  lme4::lmer(z(value) ~ cond + (1|id), .)

export_ols(u01569_mod_lmer_z_4, 
           key_effects = "cond2")
```