---
title: "Untitled"
author: "MS"
date: '2022-06-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


source("../scripts/helpers.R")

cond_names = c(
  "kor0_ooc0_soc0", 
  "kor0_ooc0_soc1",
  "kor0_ooc1_soc0",
  "kor0_ooc1_soc1",
  "kor1_ooc0_soc0",
  "kor1_ooc0_soc1",
  "kor1_ooc1_soc0",
  "kor1_ooc1_soc1")

df_1 <- read.delim("../data/raw_data/u02085_ToM_summary_RTs.txt") %>% 
  magrittr::set_colnames(
    c("id", "group", 
      cond_names
    ))

df_2 <- read.delim("../data/raw_data/u02085_ToM_summary_accuracy.txt") %>% 
  magrittr::set_colnames(
    c("id", "group", "sex", 
      cond_names
    ))

```

# 1 

```{r}
df_1_long <- df_1 %>% 
  tidyr::pivot_longer(-c(id, group)) %>% 
  dplyr::mutate(
    kor = factor(if_else( str_detect(name, "kor0"), 0, 1)), 
    ooc = factor(if_else( str_detect(name, "ooc0"), 0, 1)), 
    soc = factor(if_else( str_detect(name, "soc0"), 0, 1)), 
    group = factor(group)
  )


u02085_mod_rm_z_1 <- df_1_long %>% 
  afex::aov_4(z(value) ~ group*kor*ooc*soc + (kor*ooc*soc|id), .)

export_ols(u02085_mod_rm_z_1, 
           key_effects = c("kor", "ooc", "soc", "kor:soc", "group:kor", "group:ooc", "group:soc"))



u02085_mod_lmer_z_1 <- df_1_long %>% 
  lme4::lmer(z(value) ~ group*kor*ooc*soc + (1|id), .)

export_ols(u02085_mod_lmer_z_1, 
           key_effects = c("kor1", "ooc1", "soc1", "kor1:soc1", 
                           "group2:kor1", "group2:ooc1", "group2:soc1"))

```

# 2

```{r}
df_2_long <- df_2 %>% 
  tidyr::pivot_longer(-c(id, group, sex)) %>% 
  dplyr::mutate(
    kor = factor(if_else( str_detect(name, "kor0"), 0, 1)), 
    ooc = factor(if_else( str_detect(name, "ooc0"), 0, 1)), 
    soc = factor(if_else( str_detect(name, "soc0"), 0, 1)), 
    group = factor(group)
  )


u02085_mod_rm_z_2 <- df_2_long %>% 
  afex::aov_4(z(value) ~ group*kor*ooc*soc + (kor*ooc*soc|id), .)

export_ols(u02085_mod_rm_z_2, 
           key_effects = c("kor", "ooc", "soc", "kor:soc", "group:kor", "group:ooc", "group:soc"))



u02085_mod_lmer_z_2 <- df_2_long %>% 
  lme4::lmer(z(value) ~ group*kor*ooc*soc + (1|id), .)

export_ols(u02085_mod_lmer_z_2, 
           key_effects = c("kor1", "ooc1", "soc1", "kor1:soc1", 
                           "group2:kor1", "group2:ooc1", "group2:soc1"))
```

```{r}
mods_info_export("u02085")
```

