---
title: "Untitled"
author: "MS"
date: '2022-06-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../scripts/helpers.R")

df <- haven::read_sav("../data/raw_data/u02060_1 Final Dataset Working 20-08-24.sav") %>% 
  dplyr::mutate(
    Group_N = factor(Group_N)
  )
```


# 1 

```{r}
u02060_mod_z_1 <- df %>% 
  lm(z(M_INT_IM_NOS) ~ z(M_ATT_IM_NOS) + z(M_SN_IM_NOS) + z(M_PBC_IM_NOS), .) 

export_ols(u02060_mod_z_1, 
           key_effects = c("z(M_ATT_IM_NOS)", "z(M_SN_IM_NOS)", "z(M_PBC_IM_NOS)"))
```

# 2

I'm trying to be selective here as this looks like a thesis with over 20 hypotheses and a lot of exploratory pair-wise comparisons run as t-tests and not a single linear model. I've taken all the intervention groups and compared against a baseline on the 4 key measures (intervention, attitudes, pbc, social norms). 

```{r}
u02060_mod_z_2 <- df %>% 
  lm(z(M_ATT_IM_NOS) ~ Group_N, .) 

export_ols(u02060_mod_z_2, 
           key_effects = c("Group_N1", "Group_N2", "Group_N3",
                           "Group_N4", "Group_N5", "Group_N6"))
```

# 3

```{r}
u02060_mod_z_3 <- df %>% 
  lm(z(M_SN_IM_NOS) ~ Group_N, .) 

export_ols(u02060_mod_z_3, 
           key_effects = c("Group_N1", "Group_N2", "Group_N3",
                           "Group_N4", "Group_N5", "Group_N6"))
```

# 4

```{r}
u02060_mod_z_4 <- df %>% 
  lm(z(M_PBC_IM_NOS) ~ Group_N, .) 

export_ols(u02060_mod_z_4, 
           key_effects = c("Group_N1", "Group_N2", "Group_N3",
                           "Group_N4", "Group_N5", "Group_N6"))
```

# 5 

```{r}
u02060_mod_z_5 <- df %>% 
  lm(z(M_INT_IM_NOS) ~ Group_N, .) 

export_ols(u02060_mod_z_5, 
           key_effects = c("Group_N1", "Group_N2", "Group_N3",
                           "Group_N4", "Group_N5", "Group_N6"))

```

