---
title: "u02554"
author: "MS"
date: '2022-06-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../scripts/helpers.R")

data_mask_pol <- readRDS("../data/raw_data/u02554_data_mask_pol.rds")

```


Model 1

```{r}
u02554_mod_z_1 <- lm(z(MASK_PROT_SELF) ~ z(POL_NONE_C)*FAKTOR_MASK, data = data_mask_pol) 

export_ols(u02554_mod_z_1, 
           key_effects = c("z(POL_NONE_C)", 
                           "FAKTOR_MASKInfograhic present", 
                           "z(POL_NONE_C):FAKTOR_MASKInfograhic present"))
```

model 2

```{r}
u02554_mod_z_2 <- lm(z(MASK_PROT_OTHER)~ z(POL_NONE_C)*FAKTOR_MASK, data = data_mask_pol) 

export_ols(u02554_mod_z_2, 
           key_effects = c("z(POL_NONE_C)", 
                           "FAKTOR_MASKInfograhic present", 
                           "z(POL_NONE_C):FAKTOR_MASKInfograhic present"))
```

model 3

```{r}
u02554_mod_z_3 <- lm(z(MASK_EFFECTIVE_REASONABLE)~ z(POL_NONE_C)*FAKTOR_MASK, data = data_mask_pol) 

export_ols(u02554_mod_z_3, 
           key_effects = c("z(POL_NONE_C)", 
                           "FAKTOR_MASKInfograhic present", 
                           "z(POL_NONE_C):FAKTOR_MASKInfograhic present"))
```

model 4

```{r}
u02554_mod_z_4 <- lm(z(MASK_COMFORTABLE_NICE)~ z(POL_NONE_C)*FAKTOR_MASK, data = data_mask_pol) 

export_ols(u02554_mod_z_4, 
           key_effects = c("z(POL_NONE_C)", 
                           "FAKTOR_MASKInfograhic present", 
                           "z(POL_NONE_C):FAKTOR_MASKInfograhic present"))
```



