---
title: "Untitled"
author: "MS"
date: '2022-07-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

df <- haven::read_sav("../data/raw_data/u03812_PDnavpaperuploaded.sav") %>% 
  dplyr::mutate(id = 1:nrow(.))
```

model 1 

```{r}
u03812_mod_z_1 <- df %>% 
  dplyr::filter(usedevtraj == 1) %>% 
  lm(z(MonkeyMeanPropCorrect) ~ factor(Physical_disability)*BASASminus58, .) 

export_ols(u03812_mod_z_1, 
           key_effects = c("factor(Physical_disability)2", "factor(Physical_disability)3", 
                           "BASASminus58", "factor(Physical_disability)2:BASASminus58",
                           "factor(Physical_disability)3:BASASminus58"))
```

model 2 

```{r}
u03812_mod_z_2 <- df %>% 
  dplyr::filter(usedevtraj == 1) %>% 
  lm(Beebot_games ~ factor(Physical_disability)*BASASminus58, .) 

export_ols(u03812_mod_z_2, 
           key_effects = c("factor(Physical_disability)2", "factor(Physical_disability)3", 
                           "BASASminus58", "factor(Physical_disability)2:BASASminus58",
                           "factor(Physical_disability)3:BASASminus58"))
```

model 3

```{r}
df_long <- df %>% 
  dplyr::filter(!id %in% c(125, 171, 172, 174)) %>% 
  dplyr::select(id, wheel_use_collapsed, corandincjunc, corandincpath) %>% 
  tidyr::pivot_longer(cols = -c(id, wheel_use_collapsed)) |> 
  dplyr::mutate(wheel_use_collapsed = factor(wheel_use_collapsed))

u03812_mod_rm_z_3 <- df_long %>% 
  afex::aov_4(value ~ name*wheel_use_collapsed + (name|id), .)

export_ols(
  u03812_mod_rm_z_3, 
  key_effects = c("wheel_use_collapsed", "name", "wheel_use_collapsed:name")
)

u03812_mod_lmer_z_3 <- df_long %>% 
  lme4::lmer(value ~ name*wheel_use_collapsed + (1|id), .)

export_ols(
  u03812_mod_lmer_z_3, 
  key_effects = mod_coeffs(u03812_mod_lmer_z_3)
)
```

